// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAuthMeData, GetAuthMeResponses, GetData, GetHealthData, GetHealthResponses, GetResponses, PostAuthLoginOtpRequestData, PostAuthLoginOtpRequestResponses, PostAuthLoginOtpVerifyData, PostAuthLoginOtpVerifyResponses, PostAuthLoginPasswordData, PostAuthLoginPasswordResponses, PostAuthRefreshData, PostAuthRefreshResponses } from './types.gen';
import { zGetAuthMeData, zGetData, zGetHealthData, zPostAuthLoginOtpRequestData, zPostAuthLoginOtpVerifyData, zPostAuthLoginPasswordData, zPostAuthRefreshData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postAuthLoginPassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginPasswordData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginPasswordResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginPasswordData.parseAsync(data),
    url: '/auth/login/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLoginOtpRequest = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginOtpRequestData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginOtpRequestResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginOtpRequestData.parseAsync(data),
    url: '/auth/login/otp/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLoginOtpVerify = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginOtpVerifyData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginOtpVerifyResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginOtpVerifyData.parseAsync(data),
    url: '/auth/login/otp/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostAuthRefreshData, ThrowOnError>) => (options.client ?? client).post<PostAuthRefreshResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthRefreshData.parseAsync(data),
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthMeData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetData.parseAsync(data),
    url: '/',
    ...options
});

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetHealthData.parseAsync(data),
    url: '/health',
    ...options
});
