// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PostAuthLoginPasswordData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login/password';
};

export type PostAuthLoginPasswordResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        refreshToken: string;
        expiresIn: number;
        tokenType: string;
        user: {
            id: string;
            email: string | unknown;
            role: string;
        };
    };
};

export type PostAuthLoginPasswordResponse = PostAuthLoginPasswordResponses[keyof PostAuthLoginPasswordResponses];

export type PostAuthLoginOtpRequestData = {
    body: {
        email: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login/otp/request';
};

export type PostAuthLoginOtpRequestResponses = {
    /**
     * Default Response
     */
    202: {
        status: 'sent';
    };
};

export type PostAuthLoginOtpRequestResponse = PostAuthLoginOtpRequestResponses[keyof PostAuthLoginOtpRequestResponses];

export type PostAuthLoginOtpVerifyData = {
    body: {
        email: string;
        token: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login/otp/verify';
};

export type PostAuthLoginOtpVerifyResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        refreshToken: string;
        expiresIn: number;
        tokenType: string;
        user: {
            id: string;
            email: string | unknown;
            role: string;
        };
    };
};

export type PostAuthLoginOtpVerifyResponse = PostAuthLoginOtpVerifyResponses[keyof PostAuthLoginOtpVerifyResponses];

export type PostAuthRefreshData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        refreshToken: string;
        expiresIn: number;
        tokenType: string;
        user: {
            id: string;
            email: string | unknown;
            role: string;
        };
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * Default Response
     */
    200: {
        user: {
            id: string;
            email: string | unknown;
            role: string;
        };
    };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Default Response
     */
    200: {
        name: string;
        version: string;
        environment: 'development' | 'test' | 'production';
    };
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: {
        status: 'ok';
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
