// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPostAuthLoginPasswordData = z.object({
    body: z.object({
        email: z.string().min(1),
        password: z.string().min(1)
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zPostAuthLoginOtpRequestData = z.object({
    body: z.object({
        email: z.string().min(1)
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zPostAuthLoginOtpVerifyData = z.object({
    body: z.object({
        email: z.string().min(1),
        token: z.string().min(1)
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zPostAuthRefreshData = z.object({
    body: z.object({
        refreshToken: z.string().min(1)
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetAuthMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetHealthData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});
