// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { get, getAuthMe, getHealth, type Options, postAuthLoginOtpRequest, postAuthLoginOtpVerify, postAuthLoginPassword, postAuthRefresh } from '../sdk.gen';
import type { GetAuthMeData, GetAuthMeResponse, GetData, GetHealthData, GetHealthResponse, GetResponse, PostAuthLoginOtpRequestData, PostAuthLoginOtpRequestResponse, PostAuthLoginOtpVerifyData, PostAuthLoginOtpVerifyResponse, PostAuthLoginPasswordData, PostAuthLoginPasswordResponse, PostAuthRefreshData, PostAuthRefreshResponse } from '../types.gen';

export const postAuthLoginPasswordMutation = (options?: Partial<Options<PostAuthLoginPasswordData>>): UseMutationOptions<PostAuthLoginPasswordResponse, DefaultError, Options<PostAuthLoginPasswordData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginPasswordResponse, DefaultError, Options<PostAuthLoginPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLoginPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLoginOtpRequestMutation = (options?: Partial<Options<PostAuthLoginOtpRequestData>>): UseMutationOptions<PostAuthLoginOtpRequestResponse, DefaultError, Options<PostAuthLoginOtpRequestData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginOtpRequestResponse, DefaultError, Options<PostAuthLoginOtpRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLoginOtpRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLoginOtpVerifyMutation = (options?: Partial<Options<PostAuthLoginOtpVerifyData>>): UseMutationOptions<PostAuthLoginOtpVerifyResponse, DefaultError, Options<PostAuthLoginOtpVerifyData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginOtpVerifyResponse, DefaultError, Options<PostAuthLoginOtpVerifyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLoginOtpVerify({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, DefaultError, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, DefaultError, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, DefaultError, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

export const getQueryKey = (options?: Options<GetData>) => createQueryKey('get', options);

export const getOptions = (options?: Options<GetData>) => queryOptions<GetResponse, DefaultError, GetResponse, ReturnType<typeof getQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await get({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQueryKey(options)
});

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});
